name = "TrajTools"
uuid = "58eb31b7-200e-41ba-85be-5c947a16f695"
authors = ["Johnny Alexander Jimenez Siegert <johnny.jimenez-siegert@student.uni-halle.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
